# Generated by Django 5.2.8 on 2025-12-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.TextField(max_length=10),
        ),
    ]
