# Generated by Django 5.2.8 on 2025-12-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_cat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('amount', models.FloatField()),
                ('category', models.TextField()),
            ],
        ),
    ]
