# Generated by Django 5.2.8 on 2025-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user_img',
        ),
        migrations.AddField(
            model_name='register',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
