# Generated by Django 5.2.8 on 2025-12-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_register_user_img_register_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_expense',
            name='register_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
    ]
