# Generated by Django 5.2.8 on 2025-12-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_expense_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
