# Generated by Django 5.2.8 on 2025-12-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='register_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.register'),
        ),
    ]
